Algoritmo "faça1"
//  
//  
// Descrição   : (função) imprimir a tabela de equivalência de graus fahrenheit para centígrados.
// Autor(a)    : Rayssa
// Data atual  : 26/06/2016
Var
// Seção de Declarações das variáveis 
   i: inteiro
   F, C: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Leia (F)
   i <- i + 1
   C=5/9(F-32)
   Enquanto (F>50 e F<70) faça
   F <- C+i
   Escreva (F <- C)
   Fimenquanto
   Escreva (F=C)

Fimalgoritmo
