Algoritmo "questao11"
//  
// Descrição   : Escrever se é menor ou maior de idade ou se tem mais de 65 anos (função)
// Autor(a)    : Rayssa
// Data atual  : 17/04/2016

Var
// idade: inteiro

Inicio
 // Leia(idade)
 //Se(idade<18) então
  //Escreva("menor de idade")
 //Senão
   //Se(idade<65) então
    //Escreva("maior de idade")
   //Senão
     //Escreva("maior que 65 anos")
   //Fimse
 //Fimse
Fimalgoritmo